name: Static Code Analysis

on:
  push:
  pull_request:

jobs:
  ruff:
    name: Ruff
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: pip install ruff
      - run: ruff .

  mypy:
    name: Mypy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: pip install mypy
      - run: mypy .
