name: Static Code Analysis

on:
  push:
  pull_request:

jobs:
  ruff:
    name: SCA
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: poetry install --no-interaction --no-ansi
      - run: poetry run ruff check .
      - run: poetry run mypy .
